language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r travis_requirements.txt
script:
- pytest --cov hackr --cov-report term-missing --cov-report xml
- pytest --flakes
- pytest --pep8
- pytest --mccabe -m mccabe
- pytest --pylint -m pylint

